// Grab the element on the page to write to.
const element = document.getElementsByClassName('hello')[0];

// Call StoryTeller and pass in the element.
StoryTeller(element)

    // Then begin writing your script.
    .newNestedElement('h2')
    .write('Hello! ')
    .wait(500)
    .newLine()
    .write('Thanks for checking out StoryTeller.js.')
    .newLine()
    .newLine()
    .write('This library was created to make it easier to write dialogue like text.')
    .newElement('h4')
    .write('It was inspired by RPG\'s')
    .newElement('h2')
    .write('Here are some things currently supported.')
    .newLine()
    .newLine()
    .newElement('h2')
    .write('Pauses')
    .newElement('hr')
    .newElement('h3')
    .write('By using .wait(time) ')
    .wait(400)
    .write('you ')
    .wait(400)
    .write('can ')
    .wait(400)
    .write('pause ')
    .wait(400)
    .write('between ')
    .wait(400)
    .write('words.')
    .newLine()
    .wait(1000)
    .newElement('h2')
    .write('3 ')
    .wait(1000)
    .write('2 ')
    .wait(1000)
    .write('1 ')
    .wait(1000)
    .write('GO!')